In [2]:
import pandas as pd

In [3]:
sales=pd.read_csv(r"C:\Users\rajen\Downloads\Chocaltes_data\sales.csv")
stores=pd.read_csv(r"c:\Users\rajen\Downloads\Chocaltes_data\stores.csv")
customers=pd.read_csv(r"C:\Users\rajen\Downloads\Chocaltes_data\customers.csv")
products=pd.read_csv(r"C:\Users\rajen\Downloads\Chocaltes_data\products.csv")
calendar=pd.read_csv(r"C:\Users\rajen\Downloads\Chocaltes_data\calendar.csv")
sales.head()

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40

In [4]:
calendar.head()

         date  year  month  day  week  day_of_week
0  2023-01-01  2023      1    1    52            6
1  2023-01-02  2023      1    2     1            0
2  2023-01-03  2023      1    3     1            1
3  2023-01-04  2023      1    4     1            2
4  2023-01-05  2023      1    5     1            3

In [5]:
print(sales.dtypes,"/n",stores.dtypes,"/n",customers.dtypes,"/n",products.dtypes,"/n",calendar.dtypes)

order_id           str
order_date         str
product_id         str
store_id           str
customer_id        str
quantity         int64
unit_price     float64
discount       float64
revenue        float64
cost           float64
profit         float64
dtype: object /n store_id      str
store_name    str
city          str
country       str
store_type    str
dtype: object /n customer_id         str
age               int64
gender              str
loyalty_member    int64
join_date           str
dtype: object /n product_id         str
product_name       str
brand              str
category           str
cocoa_percent    int64
weight_g         int64
dtype: object /n date             str
year           int64
month          int64
day            int64
week           int64
day_of_week    int64
dtype: object

Checking the presence of Null and Duplicate values in the data

In [6]:
sales.isnull().sum()
sales.duplicated().sum()

np.int64(0)

In [7]:
stores.isnull().sum()
stores.duplicated().sum()

np.int64(0)

In [8]:
products.isnull().sum()
products.duplicated().sum()

np.int64(0)

In [9]:
customers.isnull().sum()
customers.duplicated().sum()

np.int64(0)

In [10]:
calendar.isnull().sum()
calendar.duplicated().sum()

np.int64(0)

There are no signs of presence of Null or duplicated values in the data

Descriptive Statistics of the data

In [11]:
sales.describe()

,quantity,unit_price,discount,revenue,cost,profit
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,2.999589,9.002449,0.056248,25.486129,15.291554,10.194565
std,1.413621,3.462902,0.076809,16.367864,9.972706,6.778760
min,1.000000,3.000000,0.000000,2.400000,1.200000,0.730000
25%,2.000000,6.000000,0.000000,12.160000,7.240000,4.780000
50%,3.000000,9.010000,0.000000,21.920000,13.030000,8.600000
75%,4.000000,12.000000,0.150000,35.880000,21.410000,14.170000
max,5.000000,15.000000,0.200000,75.000000,52.430000,37.430000

In [12]:
stores.describe()

       store_id         store_name     city country store_type
count       100                100      100     100        100
unique      100                100        7       6          4
top        S001  Chocolate Store 1  Toronto  Canada    Airport
freq          1                  1       18      20         30

In [13]:
calendar.describe()

              year       month         day        week  day_of_week
count   731.000000  731.000000  731.000000  731.000000   731.000000
mean   2023.500684    6.519836   15.738714   26.465116     2.997264
std       0.500342    3.451913    8.809949   15.076602     2.004787
min    2023.000000    1.000000    1.000000    1.000000     0.000000
25%    2023.000000    4.000000    8.000000   13.000000     1.000000
50%    2024.000000    7.000000   16.000000   26.000000     3.000000
75%    2024.000000   10.000000   23.000000   39.500000     5.000000
max    2024.000000   12.000000   31.000000   52.000000     6.000000

In [14]:
products.describe()

       cocoa_percent    weight_g
count     200.000000  200.000000
mean       69.150000  107.500000
std        14.623499   50.898954
min        50.000000   50.000000
25%        50.000000   80.000000
50%        70.000000  100.000000
75%        80.000000  120.000000
max        90.000000  200.000000

In [15]:
customers.describe()

                age  loyalty_member
count  50000.000000    50000.000000
mean      44.026100        0.502080
std       15.328333        0.500001
min       18.000000        0.000000
25%       31.000000        0.000000
50%       44.000000        1.000000
75%       57.000000        1.000000
max       70.000000        1.000000

In [18]:
products.head()

  product_id           product_name    brand category  cocoa_percent  weight_g
0      P0001    White Chocolate 80%     Mars  Truffle             80       120
1      P0002     Dark Chocolate 70%  Cadbury  Praline             70       100
2      P0003  Truffle Chocolate 70%  Hershey  Praline             70       120
3      P0004     Milk Chocolate 50%     Mars  Praline             50        80
4      P0005    White Chocolate 70%  Ferrero    White             70        50

In [24]:
products['product_name'].value_counts()

product_name
Dark Chocolate 50%       14
Truffle Chocolate 80%    13
Milk Chocolate 70%       11
Praline Chocolate 50%    11
White Chocolate 50%      10
Dark Chocolate 60%       10
White Chocolate 80%       9
Praline Chocolate 70%     9
White Chocolate 90%       9
Truffle Chocolate 90%     9
Dark Chocolate 70%        8
Milk Chocolate 50%        8
White Chocolate 70%       8
Dark Chocolate 90%        8
Truffle Chocolate 50%     8
Truffle Chocolate 70%     7
Praline Chocolate 90%     7
Milk Chocolate 60%        7
White Chocolate 60%       6
Milk Chocolate 80%        6
Milk Chocolate 90%        6
Dark Chocolate 80%        5
Praline Chocolate 60%     4
Praline Chocolate 80%     4
Truffle Chocolate 60%     3
Name: count, dtype: int64

In [22]:
products['brand'].value_counts()

brand
Cadbury    37
Ferrero    37
Lindt      35
Mars       33
Godiva     30
Hershey    28
Name: count, dtype: int64

In [23]:
products['category'].value_counts()

category
Praline    53
White      48
Dark       42
Truffle    31
Milk       26
Name: count, dtype: int64

In [25]:
stores['city'].value_counts()

city
Toronto      18
Paris        16
London       16
New York     15
Sydney       13
Melbourne    12
Berlin       10
Name: count, dtype: int64

In [26]:
stores['country'].value_counts()

country
Canada       20
UK           19
France       17
USA          17
Australia    15
Germany      12
Name: count, dtype: int64

In [27]:
stores['store_type'].value_counts()

store_type
Airport    30
Mall       26
Online     25
Retail     19
Name: count, dtype: int64